version: '3.7'

services:
  nginx:
    build: ./nginx
    tty: true
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8000:80
    volumes:
      - staticvolume:/collected-static
    networks:
      - nginx_network
    depends_on:
      - web

  web:
    build: .
    tty: true
    command: /bin/bash -c "chmod +x start.sh && /code/start.sh"
    volumes:
      - staticvolume:/collected-static
      - .:/code
    depends_on:
      - db
    networks:
      - nginx_network
      - db_network
    expose:
      - 8000
    environment:
      - ENV=dev
    env_file:
      - .env
